from typing import TypedDict, List

class AnalysisState(TypedDict, total=False):
     # Input from FastAPI
    repo_url: str

    # Generated by fetch_repo_node
    temp_dir: str
    repo_dir: str

    # Generated later by extract_php_files_node
    php_files: List[str]

    # Generated by analysis nodes
    current_file: str
    routes: List[str]