from typing import TypedDict, List, Dict, Any

class AnalysisState(TypedDict, total=False):
     # Input from FastAPI
    repo_url: str

    # Generated by fetch_repo_node
    temp_dir: str
    repo_dir: str

    # Generated later by extract_php_files_node
    php_files: List[str]

    # Generated by analysis nodes
    current_file: str
  
    # NEW — the list of vulnerability entries returned by the LLM
    vulnerabilities: List[Dict[str, Any]]

     # Generated by save_output_node
    output_file: str